/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "BasicTimer.h"
#include "GPIOxDriver.h"

/* Definición de los elementos del sistema */

GPIO_Handler_t handlerLED2 = {0};

GPIO_Handler_t handlerUserButton = {0};

BasicTimer_Handler_t handlerBlinkyTimer = {0};
uint32_t counterExti13 = 0;

void init_Hardware(void);
void callback_exti13(void);

int main(void){

	init_Hardware();

	while(1){

	}

	return 0;
}

void init_Hardware(void){
	//Se configura el LED 2 como LED de estado
	handlerLED2.pGPIOx 								= GPIOA;
	handlerLED2.GPIO_PinConfig.GPIO_PinNumber		= PIN_5;
	handlerLED2.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	handlerLED2.GPIO_PinConfig.GPIO_PinOPType		= GPIO_OTYPE_PUSHPULL;
	handlerLED2.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	handlerLED2.GPIO_PinConfig.GPIO_PinSpeed		= GPIO_OSPEED_MEDIUM;

	//Se carga la configuración del LED 2
	GPIO_Config(&handlerLED2);

	GPIO_WritePin(&handlerLED2, SET);

	//Se configura el timer 2
	handlerBlinkyTimer.ptrTIMx 				 			= TIM2;
	handlerBlinkyTimer.TIMx_Config.TIMx_mode 			= BTIMER_MODE_UP;
	handlerBlinkyTimer.TIMx_Config.TIMx_speed			= BTIMER_SPEED_1ms;
	handlerBlinkyTimer.TIMx_Config.TIMx_period  		= 300;
	handlerBlinkyTimer.TIMx_Config.TIMx_interruptEnable = BTIMER_INTERRUPT_ENABLE;

	//Se carga la configuración del TIM 2 en los registros
	BasicTimer_Config(&handlerBlinkyTimer);

	handlerUserButton.pGPIOx = GPIOC;
	handlerUserButton.GPIO_PinConfig.GPIO_PinNumber			= PIN_13;
	handlerUserButton.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_IN;
	handlerUserButton.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;

	GPIO_Config(&handlerUserButton);

	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	SYSCFG->EXTICR[3] &= ~(0xF << SYSCFG_EXTICR4_EXTI13_Pos);
	SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;

	EXTI->FTSR = 0;
	EXTI->RTSR = 0;
	EXTI->RTSR |= EXTI_RTSR_TR13;

	EXTI->IMR = 0;
	EXTI->IMR |= EXTI_IMR_IM13;

	__disable_irq();

	NVIC_EnableIRQ(EXTI15_10_IRQn);



}

void callback_exti13(void){
	counterExti13++;
}

void EXTI15_10_IRQHandler(void){

	if((EXTI->PR & EXTI_PR_PR13) != 0){
		EXTI->PR |= EXTI_PR_PR13;
		callback_exti13();
	}


}

void BasicTimer2_Callback(void){
	GPIOxTooglePin(&handlerLED2);
}
