/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xx_hal.h"



int main(void){

	//Configuracion inicial del MCU
	RCC->AHB1ENR &= ~(1 << 0); //Limpiando la posicion 0 del registro
	RCC->AHB1ENR |= (1 << 0);  //Activamos la señal del reloj del GPIOA

	//Configurando el pin PA5 como salida
	GPIOA->MODER &= ~(0b11 << 10);
	GPIOA->MODER |= (0b01 << 10);

	GPIOA->OTYPER &= ~(1 << 5);


	GPIOA->OSPEEDR &= ~(0b11 << 10);
	GPIOA->OSPEEDR |= ~(0b10 << 10);

	GPIOA->PUPDR &= ~(0b11 <<10);

	GPIOA->ODR &= ~(1 << 5);
	GPIOA->ODR |= (1 << 5);

   while(1){

   }
   return 0;

}

