/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "BasicTimer.h"
#include "GPIOxDriver.h"

// Se define y se inicializa el elemento.
GPIO_Handler_t handlerOnBoardLed = {0};

BasicTimer_Handler_t handlerTim2 = {0};

/* Se ajustan los parámetros
 * de la función central del programa
 */
int main(void){

  /* Configuración del LED 2 del microcontrolador */
	handlerOnBoardLed.pGPIOx 								= GPIOA;
	handlerOnBoardLed.GPIO_PinConfig.GPIO_PinNumber			= PIN_5;
	handlerOnBoardLed.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	handlerOnBoardLed.GPIO_PinConfig.GPIO_PinOPType			= GPIO_OTYPE_PUSHPULL;
	handlerOnBoardLed.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	handlerOnBoardLed.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_OSPEED_FAST;

	// Se selecciona el TIMER que se elegió trabajar en el programa.
	handlerTim2.ptrTIMx 	= TIM2;

	// Configuración general en que se va a manejar el timer.
	handlerTim2.TIMx_Config.TIMx_mode			= BTIMER_MODE_UP;
	handlerTim2.TIMx_Config.TIMx_period			= 5000;
	handlerTim2.TIMx_Config.TIMx_speed			= BTIMER_SPEED_1ms;

	// Se carga lo que se hizo sobre el pin A5
	GPIO_Config(&handlerOnBoardLed);
	GPIO_WritePin(&handlerOnBoardLed, SET);

	/* Se carga ahora la configuración del TIMER */
	BasicTimer_Config(&handlerTim2);

	while(1){

	}
}
void BasicTimerX_Callback(void){
	GPIOxTooglePin(&handlerOnBoardLed);
}






