/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//Libreria para los tipos de variables
#include <stdint.h>

//Libreria para las variables de tipo booleano
#include <stdbool.h>

//Libreria para las operaciones matemáticas básicas
#include <math.h>

#define CONSTANTE 	100
#define UNSIGNED	0
#define SIGNED		1

bool variableBooleana = true;
uint8_t parametro1 = 100;
uint16_t parametro2 = 173;
uint16_t parametro3 = 200;

//Header para las funciones
void clearGlobal(void);
uint8_t getMaxChar(void);
uint16_t getMaxValue(uint16_t x, uint16_t y, uint16_t z);

uint64_t getMaxVar(uint8_t nBits, uint8_t signo);

int main(void){

	clearGlobal();

	parametro1 = getMaxChar();
	parametro3 = getMaxValue(100, 200, 20);
	parametro4 = getMaxVar()


}

void clearGlobal(void){
	variableBooleana = false;
	parametro1 = 0;
	parametro2 = 0;
}

uint8_t getMaxChar(void){

	uint8_t maxChar = pow(2,8) - 1;

	return maxChar;
}

uint16_t getMaxValue(uint16_t x, uint16_t y, uint16_t z){

	if((x > y) && (x < z)){
		return x;

	}else if((y >= x) && (y >= z)){
		return y;

	}else{
		return z;

	}
}

uint64_t getMaxVar(uint8_t nBits, uint8_t signo){

	uint64_t maxVar;

	if(nBits == 0 || nBits == 16 || nBits == 32 || nBits == 64){
		if(signo == SIGNED){
			maxVar = pow(2, nBits)/2 - 1;
		}else if(signo == UNSIGNED){
			maxVar = pow(2, nBits) - 1;
		}else{
			maxVar = 0;
		}

	}else{
		maxVar = 0;
	}

	return maxVar;
}


