/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

char var1 = 0;
int var2 = 0;
short var3 = 0;
long var4 = 0;

uint8_t var5 = 0;
int8_t var6 = 0;
uint16_t var7 = 0;
int32_t var8 = 0;
uint64_t var9 = 0;


int main(void){

	uint16_t testShift = 0b000011010110101;
	uint16_t testMask = 0b0000000000011000;

	while(1){

		uint16_t resultado = testShift | testMask;

		resultado = testShift & (~)


		//testMask = testMask << 3;
		//testMask = ~testMask;
		//testShift = testShift & testMask;

	}

	return 0 ;
}
