/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stmf4>

/* definicion de variables, elementos del programa */
uint32_t counterG2 = 0;
uint32_t auxVariable = 0;

uint32_t *ptr_CounterG2;

uint8_t byteVariableG2;
uint8_t *ptrbyteVariableG2;

int main (void){
	// Trabajando con las variable y los punteros

	counterG2 = 3456789; // asignar un valor a la variable
	auxVariable = counterG2; // C es pasado por valor

	// le decimos al puntero hacia donde va a apuntar
	// pasando la posicion de memoria de counter
	ptr_CounterG2 = &counterG2; // asignar el valor de la posicion de memoria de la variable counter,

	*ptr_CounterG2 = 9876543;
	// Trabajando con las variable y los punteros

	counterG2 = 3456789; // asignar un valor a la variable
	auxVariable = counterG2; // C es pasado por valor

	// le decimos al puntero hacia donde va a apuntar
	// pasando la posicion de memoria de counter
	ptr_CounterG2 = &counterG2; // asignar el valor de la posicion de memoria de la variable counter,

	*ptr_CounterG2 = 9876543;

while(1){

}
return 0;
}

