/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/* Definición elementos del programa */
uint32_t counterG2 = 0;
uint32_t auxVariable = 0;

int32_t *ptr_CounterG2;

uint8_t byteVariableG2;
uint8_t *ptr_ByteVariableG2;


int main(void){

	/* trabajando variables y asignando punteros */
	counterG2 = 3456789;
	auxVariableG2 = counterG2;

	ptr_CounterG2 = &counterG2;

	ptr_CounterG2 = 9876543;


	while(1){


		}
	}



